services:
  web:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile.dev
    container_name: web
    volumes:
      - ./packages/frontend:/usr/src/packages/frontend:cached
      - ./packages/ui:/usr/src/packages/ui
      - ./packages/utils:/usr/src/packages/utils
      - /usr/src/packages/frontend/node_modules
      - /usr/src/packages/frontend/.next
    restart: always
    networks:
      - web-network
  admin-web:
    build:
      context: .
      dockerfile: ./packages/admin-frontend/Dockerfile.dev
    container_name: admin-web
    volumes:
      - ./packages/admin-frontend:/usr/src/packages/admin-frontend:cached
      - ./packages/ui:/usr/src/packages/ui
      - ./packages/utils:/usr/src/packages/utils
      - /usr/src/packages/admin-frontend/node_modules
    restart: always
    networks:
      - web-network
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.dev
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/common:/etc/nginx/common
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
      - admin-web
    restart: always
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
