import type { Metadata } from 'next'
import { Inter, Space_Grotesk } from 'next/font/google'
import { cn } from '@workspace/ui/lib/utils'
import { QueryClientProvider, MSWProvider } from '@/packages/providers'
import '@workspace/ui/styles/globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
})

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn(spaceGrotesk.className, 'dark')}>
      <body
        className={cn(
          inter.variable,
          spaceGrotesk.variable,
          'antialiased',
          'min-w-[343px] max-w-300 mx-auto h-dvh'
        )}
      >
        <QueryClientProvider>
          <MSWProvider>{children}</MSWProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
