root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ."
  bin = "tmp/app"
  full_bin = "./tmp/app"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]

[log]
  time = true

[watch]
  dirs = ["."]